apiVersion: v1
kind: ConfigMap
metadata:
  # Defining the name of the ConfigMap
  name: contactlist-config
  labels:
    # Adding a label to identify the application
    app: contactlist
data:
  # Setting the URL for the contact list API, to be used by our front-end container to interface with the backend
  contactlist-api: http://192.168.58.2:30050
